server:
    port: 8080
# spring:
#   data:
#     redis:
#       host:
#       port: 6379
#   datasource:
#     url: jdbc:postgresql://localhost:5432/notifications
#     username: postgres
#     password: postgres
#   jpa:
#     hibernate:
#       ddl-auto: update
#     show-sql: true
